### ISSUE TITLE
Plugin shows up under incompatible plugins after installation

### ISSUE THREAD

**Issue by priocomdevops** [manne65-hd/Kanboard-SortBoardByDates#4]
The plugin shows as incompatible after installation.
What could be the issue?
Kind regards.

**Comment by manne65-hd** [comment]
> The plugin shows as incompatible after installation.

Can you tell me where exactly this "incompatible"-message appears? _(Maybe with a screenshot)_

Does it work anyway ??

**What is your environment ?**
- Version of Kanboard ?
- Docker-Installation ?
- Database ?
- etc. ??

**Comment by priocomdevops** [comment]
Thanks for your reply.
Please find attached.
![sort-board-by-dates-error](https://user-images.githubusercontent.com/68004624/116776586-c9499080-aa71-11eb-9642-0685950a844a.png)
![kanboard-settings](https://user-images.githubusercontent.com/68004624/116776589-ccdd1780-aa71-11eb-8d10-e3b6623252ae.png)

**Comment by manne65-hd** [comment]
Sorry ... was pretty busy the last couple of days.
Well the answer is pretty simple ... My latest version of the plugin runs with Kanboard from verison 1.2.18 and newer.

**You are running Kanboard 1.2.16**
You have 2 options to resolve the issue ...
- Quick & dirty
  -  Use [version 0.7.0 of my plugin](https://github.com/manne65-hd/Kanboard-SortBoardByDates/releases/tag/v0.7.0), which will work with your version of Kanboard
- The real solution
  - Update your Kanboard-installation to the latest version, which will then also run the latest version of my plugin :-)

### ATTENTION 
Be sure to make backups of your files and database before updating!!
And as I can see that you are using sqlite as database ... [make sure to read this](https://github.com/kanboard/kanboard/issues/4687) and you'd be best off, by directly updating from 1.2.16 to 1.2.19!

Anyway ... [read this before updating](https://docs.kanboard.org/en/latest/admin_guide/upgrade.html)!
